"Tabs
set tabstop=4 		"width of tab character 
set softtabstop=4	"Fine tunes the amount of white space to be added"
set shiftwidth=4	"Determines the amount of whitespace to add in normal mode: shift+>> or shift + <<"
set expandtab		"When this option is enabled, vi will use spaces instead of tabs"

set number          "set line number"
set autoindent      "set autoindent: doen't interfare with other indents"

"For YouCompleteMe plugin
set nocompatible    " be iMproved, required
filetype off        " required

set rtp+=~/.vim/bundle/Vundle.vim " set the runtime path to include Vundle and initialize"

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'preservim/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ycm-core/YouCompleteMe'
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" YouCompleteMe settings
let g:ycm_clangd_binary_path="/home/p/bin/dotfiles/vim/bundle/YouCompleteMe/third_party/ycmd/third_party/clangd/output/bin"
" Let clangd fully control code completion
let g:ycm_clangd_uses_ycmd_caching = 0
 " Use installed clangd, not YCM-bundled clangd which doesn't get updates.
"let g:ycm_clangd_binary_path = exepath("clangd")

let g:ycm_global_ycm_extra_conf = '/home/p/bin/dotfiles/vim/bundle/.ycm_extra_conf.py'

"let g:ycm_global_ycm_extra_conf = 
"key remap
nnoremap ; :
"n means in normal mode 
"au VimEnter * !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
"au VimLeave * !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'
map <F9> :!g++ -std=c++11 -pipe -O2 -lm -s -fomit-frame-pointer -g  % && ./a.out <CR>
